### PR TITLE
`embedding_wrapper.c` and `julia_init.c`: Use `JULIA_DEPOT_PATH` and `JULIA_LOAD_PATH` from the environment

### LINKED ISSUE #910: Can't the JULIA_DEPOT_PATH be changed in apps?
Hello,

I am building an app in a docker container and then try to run it via singularity. The app builds successfully but can't run because the `DEPOT_PATH` seems to be hardlinked to the app's `share` folder. Whether I do:

```bash
./tmle/bin/TargetedEstimation --help
```

or

```bash
JULIA_DEPOT_PATH=/opt ./TargetedEstimation --help # or export JULIA_DEPOT_PATH=/opt
```

Scratch.jl which I think is supposed to write to the `DEPOT_PATH` seems to be tryiing to append the `scratch_usage.toml` in `/TargetedEstimation.jl/tmle/share/julia/logs/`.

Can I do anything to fix this? Thanks!

Full stacktrace:

```julia
fatal: error thrown and no exception handler available.
InitError(mod=:OpenML, error=Base.SystemError(prefix="opening file "/TargetedEstimation.jl/tmle/share/julia/logs/scratch_usage.toml"", errnum=30, extrainfo=nothing))
#systemerror#83 at ./error.jl:176
systemerror at ./error.jl:176
systemerror at ./error.jl:176
#systemerror#82 at ./error.jl:175 [inlined]
systemerror at ./error.jl:175 [inlined]
#open#705 at ./iostream.jl:293
open at ./iostream.jl:275 [inlined]
#open#409 at ./io.jl:393
open at ./io.jl:392 [inlined]
track_scratch_access at /opt/packages/Scratch/NVOrR/src/Scratch.jl:178
get_scratch! at /opt/packages/Scratch/NVOrR/src/Scratch.jl:240
macro expansion at /opt/packages/Scratch/NVOrR/src/Scratch.jl:306 [inlined]
__init__ at /opt/packages/OpenML/zbyTP/src/OpenML.jl:16
jfptr___init___114432 at /TargetedEstimation.jl/tmle/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
jl_module_run_initializer at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:75
_finish_julia_init at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/init.c:855
julia_init at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/init.c:804
ijl_init_with_image at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/jlapi.c:66 [inlined]
ijl_init_with_image at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/jlapi.c:55
ijl_init at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/jlapi.c:82
main at ./tmle/bin/TargetedEstimation (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at ./tmle/bin/TargetedEstimation (unknown line)
```

### PR DESCRIPTION
**Pull request by kpamnany**
Previously, both the embedding wrapper and `julia_init.c` ignored any existing values set in the environment variables `JULIA_LOAD_PATH` and `JULIA_DEPOT_PATH`; `set_depot_load_path` simply set these up to find libraries as intended by `PackageCompiler.jl`.

However, an app might want to install packages in other locations and have those locations specified via the environment.

This PR modifies `set_depot_load_path` to append `PackageCompiler.jl`'s desired paths to `JULIA_LOAD_PATH` and `JULIA_DEPOT_PATH` rather than overwriting them.

Closes #910.

### CODE REVIEW

**Comment by kpamnany** [comment]
The [CI failure on `nightly`]() seems to be due to an upstream change -- the `alloc` parameter to `jl_get_binding_wr()` was [removed](https://github.com/JuliaLang/julia/pull/57150/files#diff-42a3fc6ebd78315e40602ab4108f5cd380ada14ff81987b696d7b4ee9372a4deR2005). I'm not sure how this should be fixed, but it is unrelated to this PR.

**Comment by kpamnany** [comment]
Bump. Can this be reviewed please? @KristofferC? Someone else?

File: src/julia_init.c [hunk 1]
```diff
@@ -46,19 +46,39 @@ void set_depot_load_path(const char *root_dir) {
...
-    strcat(share_dir, julia_share_subdir);
+    int share_path_len = strlen(root_dir) + strlen(julia_share_subdir) + 1;
+
+    char *curr_depot_path = getenv("JULIA_DEPOT_PATH");
+    int curr_depot_path_len = curr_depot_path == NULL ? 0 : strlen(curr_depot_path);
+    int new_depot_path_len = curr_depot_path_len + 1 + share_path_len;
+    char *new_depot_path = calloc(sizeof (char), new_depot_path_len);
+    if (curr_depot_path_len > 0) {
+        strcat(new_depot_path, curr_depot_path);
+        strcat(new_depot_path, ":");
```
Comment (KristofferC) [inline src/julia_init.c:57]: This should be `;` on Windows I think?

**Comment by KristofferC** [comment]
Not to be a pain, but always nice with a test to make sure the intended use case doesn't break in the future..

File: src/julia_init.c (hunk 1 above)
Comment (kpamnany) [reply src/julia_init.c]: Good catch, thanks!

**Comment by kpamnany** [comment]
> Not to be a pain, but always nice with a test to make sure the intended use case doesn't break in the future..

You're absolutely right. Will add one.

**Comment by kpamnany** [comment]
BTW, looks like the CI workflow needs updating. All of CI has failed because:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

**Comment by kpamnany** [comment]
I was unable to test locally:
```
fatal: error thrown and no exception handler available.                                    
InitError(mod=:OpenSSL_jll, error=ErrorException("could not load library \"@rpath/libcrypto.3.dylib\"\ndlopen(@rpath/libcrypto.3.dylib, 0x0001): tried: '/private/var/folders/94/8yjg0k
414zn6h3k8443yhr9w0000gn/T/jl_RFxxru/MyAppCompiled/lib/julia/libcrypto.3.dylib' (no such file), '/private/var/folders/94/8yjg0k414zn6h3k8443yhr9w0000gn/T/jl_RFxxru/MyAppCompiled/lib/j
ulia/../libcrypto.3.dylib' (no such file), '/private/var/folders/94/8yjg0k414zn6h3k8443yhr9w0000gn/T/jl_RFxxru/MyAppCompiled/lib/libcrypto.3.dylib' (no such file), '/private/var/folde
rs/94/8yjg0k414zn6h3k8443yhr9w0000gn/T/jl_RFxxru/MyAppCompiled/lib/julia/libcrypto.3.dylib' (no such file)"))
```
Any suggestions?

**Comment by DilumAluthge** [comment]
Are you able to test `PackageCompiler#master` locally?

**Comment by kpamnany** [comment]
> Are you able to test `PackageCompiler#master` locally?

No, when I tried, I got the error I posted above. Any idea about that?

I'll try again, because it looks like the test needs debugging.

**Comment by kpamnany** [comment]
I was running on Mac. Moved to Linux and was able to test. 🤷‍♂️ 

The Windows failures are because of path munging:
```
occursin("LOAD_PATH = [\"C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\jl_CXxD8T", "...]\nLOAD_PATH = [\"C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\jl_CXxD8T\",...")
```
 Any pointers to how to normalize paths with the correct number of escapes? Someone must have already written code to do this, right?

**Comment by kpamnany** [comment]
Okay, figured that one out -- the answer is `escape_string`.

Now what's broken is that `julia_init` is actually gone from Julia 1.12 -- removed by https://github.com/JuliaLang/julia/pull/58231. I think it needs to be replaced here by something like:
```julia
    jl_resolve_sysimg_location(JL_IMAGE_CWD, NULL);
    jl_image_buf_t sysimage = jl_preload_sysimg(jl_options.image_file);

    jl_init_(sysimage);
```
But I'm not really sure. Ideally, there should be a separate PR to get `PackageCompiler.jl` to work with 1.12. @DilumAluthge: any suggestions on who could help with this? Also cc: @gbaraldi who removed `julia_init`.

**Comment by kpamnany** [comment]
Bump. Paging @gbaraldi!

**Comment by kpamnany** [comment]
I cherry-picked the relevant commit (thanks @visr) but still failures on `nightly`. E.g. from [here](https://github.com/JuliaLang/PackageCompiler.jl/actions/runs/16678875186/job/47212338788?pr=1032#step:5:472):
```
fatal: error thrown and no exception handler available.
Core.InitError(mod=:Curl, error=ErrorException("could not load library \"/tmp/jl_ZGNyky/MyAppCompiled/bin/../lib/julia/libcrypto.so.3\"\n/tmp/jl_ZGNyky/MyAppCompiled/bin/../lib/julia/libcrypto.so.3: cannot open shared object file: No such file or directory"))
```
There's also [this error](https://github.com/JuliaLang/PackageCompiler.jl/actions/runs/16678875186/job/47212338788?pr=1032#step:5:1356):
```
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/julia_init.c: In function ‘init_julia’:
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/julia_init.c:100:5: error: implicit declaration of function ‘jl_init_’; did you mean ‘jl_init’? [-Werror=implicit-function-declaration]
  100 |     jl_init_(sysimage);
      |     ^~~~~~~~
      |     jl_init
```
So, still can't proceed here. :-(

**Comment by gbaraldi** [comment]
Oh that function is in the private julia-internal.h header

**Comment by kpamnany** [comment]
Is the prototype for `jl_init_` being moved out of `julia_internal.h` or is some other solution planned for 1.12?

**Review by KristofferC — APPROVED** [review]
The changes are fine for what the goal is. We kind of have the same discussion in https://github.com/JuliaLang/Pkg.jl/issues/4377 w.r.t Pkg apps, where I claimed that it is up to the app to set the depot / load path if it wants to act like a package manager.

But this probably works as well.
